baseURL = "https://sc.zeal8bit.com/"
publishDir = "_site"
disablePathToLower = true
disableKinds = ["taxonomy", "term", "robotsTXT"]

[taxonomies]

[mediaTypes."text/markdown"]
suffixes = ["md"]

[outputFormats.README]
mediaType = "text/markdown"
baseName = "README"
isPlainText = true
notAlternative = true

[outputFormats.RSS]
baseName = "rss"

[outputs]
home = ["HTML", "README", "RSS"]

[module]
[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "images"
target = "static/images"

[[module.mounts]]
source = "collection.yml"
target = "data/collection.yml"
