name: Deploy to GitHub Pages
description: Upload and deploy to GitHub Pages
inputs:
  deploy-path:
    description: 'Path to deploy'
    required: false
    default: .deploy
outputs:
  page_url:
    description: URL of the deployed GitHub Pages site
    value: ${{ steps.deploy.outputs.page_url }}
runs:
  using: "composite"
  steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.deploy-path }}

    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/deploy-pages@v4
