name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - feature/zde-deps
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Build site
        run: hugo

      - name: Deploy site
        id: deploy
        uses: ./.github/actions/deploy-pages
        with:
          deploy-path: _site/
